blank_issues_enabled: false  # hide "Open a blank issue" to funnel via templates/links

contact_links:
  - name: "Questions / ideas"
    url: https://github.com/essencenetworks/llmlog/discussions 
    about: "Use Discussions for Q&A and proposals."

  - name: "Commercial support request (private, via Asana)"
    url: https://form.asana.com/?k=3ojsZ-RsXFM3RZnTAwXI5w&d=1126911063467662 
    about: "Implementation help, training, or enterprise integration."

  - name: "Report a security vulnerability (private)"
    url: ../../security/advisories/new
    about: "Opens GitHub’s private report form; visible only to maintainers."
